apiVersion: apps/v1
kind: Deployment
metadata:
  name: camunda-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camunda-engine
  template:
    metadata:
      labels:
        app: camunda-engine
    spec:
      containers:
      - name: camunda-engine
        image: richardsobreiro/camunda-engine-app:latest
        ports:
          - containerPort: 8989
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/dev
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 2048m
            memory: 1024Mi
          requests:
            cpu: 1024m
            memory: 512Mi
      dnsPolicy: Default
---
apiVersion: v1
kind: Service
metadata:
  name: camunda-engine
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-005bf742c928e4565, subnet-09ffa57715ccf3113, subnet-05cbc0f92ca3c0006
spec:
  ports:
    - port: 80
      targetPort: 8989
      protocol: TCP
  type: NodePort
  selector:
    app: camunda-engine
           