aws:
   response-queue: https://sqs.sa-east-1.amazonaws.com/991345343226/response-queue.fifo
   requests-topic: arn:aws:sns:sa-east-1:991345343226:requests-topic.fifo

spring.datasource:
   url: jdbc:mysql://localhost:3306/camundadb
   username: root
   password: root
   driver-class-name: com.mysql.jdbc.Driver
  #url: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#shareable h2 database: jdbc:h2:./camunda-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
  #username: sa
  #password: sa
spring.h2.console.enabled: true

camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
#  default-serialization-format: application/json
server.port: 8989
